name: Trigger Pipeline

on:
  push:
    branches:
      - dev
      - staging
    tags:
      - "release-*"

jobs:
  dev:
    if: github.ref == 'refs/heads/dev'
    uses: nvlannasik/github-action-manifest/.github/workflows/dev-cicd.yml@master

  staging:
    if: github.ref == 'refs/heads/staging'
    uses: nvlannasik/github-action-manifest/.github/workflows/staging-cicd.yml@master
